"""Embedded wordlist for credential generation.

Curated list of ~500 short, memorable English words (3–6 letters). Enough
entropy when combined with digits + specials for a 16-char password on a
local-network UI. Not sourced from password cracking lists.
"""

from __future__ import annotations

WORDLIST: tuple[str, ...] = (
    "able", "acid", "acre", "ally", "amber", "angel", "angle", "ankle", "annex",
    "apex", "apple", "april", "apron", "arbor", "arc", "arch", "arena", "arm",
    "arrow", "art", "ash", "aspen", "astra", "atlas", "atom", "aunt", "axe",
    "axle", "azure", "back", "bacon", "badge", "bagel", "bake", "bald", "ball",
    "balm", "banjo", "bank", "barn", "basin", "basis", "bass", "bat", "bath",
    "beach", "bead", "beak", "bear", "beat", "beef", "beet", "bell", "belt",
    "bench", "bend", "berry", "bike", "bill", "bin", "birch", "bird", "bison",
    "black", "blade", "blast", "blaze", "blend", "bless", "blimp", "blink",
    "block", "bloom", "blue", "blush", "board", "boat", "body", "bog", "bold",
    "bolt", "bone", "book", "boom", "boot", "bore", "born", "boss", "bot",
    "botan", "bough", "bowl", "box", "boy", "brace", "brain", "branch", "brand",
    "brass", "brave", "bread", "break", "breed", "brick", "bride", "brief",
    "bring", "brisk", "broad", "broom", "brown", "brush", "buck", "bud",
    "buddy", "buff", "bulb", "bulge", "bulk", "bull", "bunch", "burn", "burst",
    "bush", "bust", "busy", "butt", "cable", "cacao", "cache", "cadet", "cafe",
    "cage", "cake", "calf", "calm", "camel", "camp", "candy", "cane", "canoe",
    "canon", "canopy", "cape", "car", "carb", "card", "care", "cargo", "carol",
    "carry", "cart", "carve", "case", "cash", "cast", "cat", "cater", "cave",
    "cedar", "cell", "chain", "chair", "chalk", "chant", "charm", "chart",
    "chase", "cheap", "cheek", "cheer", "chef", "cherry", "chess", "chest",
    "chick", "chief", "chill", "chip", "choir", "choose", "chop", "chord",
    "chrome", "chunk", "cider", "cigar", "city", "civic", "clam", "clan",
    "clap", "clash", "class", "claw", "clay", "clean", "clear", "cleat",
    "clerk", "cliff", "climb", "cling", "clip", "cloak", "clock", "clone",
    "close", "cloth", "cloud", "clove", "club", "cluck", "clump", "clutch",
    "coach", "coal", "coast", "coat", "cobra", "cocoa", "code", "coil", "coin",
    "comet", "comic", "coral", "cord", "cork", "corn", "cost", "cotton",
    "couch", "cough", "count", "court", "cove", "cow", "crab", "crack",
    "craft", "cramp", "crane", "crash", "crate", "crave", "crawl", "crazy",
    "cream", "crew", "crib", "cricket", "crisp", "crop", "cross", "crow",
    "crowd", "crown", "crumb", "crush", "crust", "cry", "crypt", "cube",
    "cue", "cup", "curl", "curry", "curse", "curve", "cycle", "daisy", "dance",
    "dandy", "dart", "dash", "data", "dawn", "day", "deal", "deck", "decoy",
    "deer", "delta", "dense", "desk", "diary", "dice", "dig", "dim", "dime",
    "diner", "dino", "dirt", "disco", "dish", "disk", "ditch", "dive", "dock",
    "dodge", "doe", "dog", "doll", "dome", "donor", "doom", "door", "dose",
    "doubt", "dough", "dove", "dozen", "draft", "drag", "drake", "drama",
    "draw", "dread", "dream", "dress", "drift", "drill", "drink", "drip",
    "drive", "drop", "drum", "dry", "duck", "dune", "dusk", "duty", "dwarf",
    "eagle", "early", "earn", "earth", "east", "easy", "eat", "ebony", "echo",
    "eden", "edge", "egg", "eight", "elbow", "elder", "elegy", "elf", "elm",
    "elope", "elven", "ember", "emoji", "emu", "enjoy", "entry", "envoy",
    "epic", "equal", "error", "essay", "eve", "even", "exit", "eye", "face",
    "fact", "fade", "faint", "fair", "falcon", "fall", "false", "fame",
    "fancy", "far", "farm", "fast", "fate", "fault", "feast", "feat", "fee",
    "feed", "feet", "fence", "fern", "ferry", "fetch", "few", "field",
    "fig", "fight", "film", "final", "find", "fine", "finch", "finger",
    "fir", "fire", "firm", "first", "fish", "fit", "five", "flag", "flake",
    "flame", "flash", "flask", "flat", "flax", "flee", "fleet", "flesh",
    "flex", "flies", "flint", "flip", "flock", "flood", "floor", "flora",
    "flour", "flow", "flute", "fly", "foam", "fog", "foil", "fold", "folk",
    "food", "fool", "foot", "force", "ford", "forge", "fork", "form", "fort",
    "forum", "fowl", "fox", "frame", "free", "fresh", "frog", "front",
    "frost", "fruit", "fry", "fudge", "fun", "fur", "fuse", "fuzzy", "gain",
    "gala", "game", "gap", "garden", "gas", "gate", "gaze", "gear", "gem",
    "gene", "genie", "gentle", "germ", "ghost", "giant", "gift", "gills",
    "giraffe", "girl", "glad", "glare", "glass", "glaze", "glee", "glen",
    "glide", "glitch", "globe", "gloom", "glory", "glove", "glow", "glue",
    "gnat", "goal", "goat", "gold", "golf", "gone", "gong", "good", "goose",
    "gorge", "gouda", "grade", "grain", "grand", "grant", "grape", "grass",
    "grate", "grave", "gravy", "gray", "great", "greed", "green", "greet",
    "grid", "grim", "grin", "grip", "grit", "groan", "grove", "grow", "grub",
    "guard", "guess", "guest", "guide", "guild", "gulf", "gull", "gulp", "gum",
    "guru", "gust", "habit", "hail", "hair", "half", "hall", "halo", "hand",
    "hang", "happy", "harbor", "hare", "harp", "harsh", "haste", "hat",
    "hatch", "hate", "haven", "havoc", "hawk", "hay", "haze", "head", "heap",
    "heart", "heat", "heavy", "hedge", "heel", "helm", "help", "hemp", "herd",
    "hero", "hide", "high", "hill", "hint", "hip", "hive", "hoard", "hobby",
    "hog", "hold", "hole", "holly", "holy", "home", "honey", "hood", "hook",
    "hoop", "hope", "horn", "horse", "host", "hot", "hotel", "hound", "hour",
    "house", "hover", "howl", "hub", "hue", "huff", "huge", "hum", "human",
    "humid", "humor", "hump", "hunt", "hurry", "hurt", "husky", "hut", "ice",
    "icon", "idea", "idol", "iguana", "inch", "index", "indoor", "inlet",
    "input", "iris", "iron", "island", "ivory", "ivy", "jacket", "jade",
    "jam", "jar", "jazz", "jelly", "jet", "jewel", "job", "jog", "joint",
    "joke", "jolly", "joy", "judge", "juice", "jumbo", "jump", "june",
    "jungle", "junior", "jury", "kale", "keep", "kelp", "kettle", "key",
    "kick", "kid", "kind", "king", "kiosk", "kiss", "kit", "kite", "kitten",
    "kiwi", "knack", "knee", "knife", "knight", "knob", "knock", "knot",
    "know", "koala", "lab", "label", "lace", "lake", "lamb", "lamp", "land",
    "lane", "lapel", "lard", "large", "lark", "laser", "lasso", "latch",
    "late", "latte", "laugh", "lava", "lawn", "layer", "lazy", "leaf", "lean",
    "leap", "lease", "leash", "left", "leg", "lemon", "lens", "leopard",
    "level", "lever", "liar", "lid", "life", "lift", "light", "lilac", "lily",
    "lime", "line", "linen", "link", "lion", "lip", "list", "lit", "live",
    "llama", "load", "loaf", "loan", "lobe", "lock", "lodge", "log", "long",
    "look", "loop", "loose", "lord", "lore", "lose", "loud", "lounge",
    "love", "low", "loyal", "luck", "lumber", "lump", "lunar", "lunch",
    "lure", "lush", "lute", "lyric", "mace", "macro", "made", "magic",
    "magma", "maid", "mail", "main", "major", "maker", "malt", "mango",
    "manor", "maple", "march", "mare", "mark", "marsh", "mask", "mass",
    "mast", "match", "mate", "math", "matrix", "maven", "maze", "meadow",
    "meal", "mean", "medal", "meet", "melon", "melt", "memo", "merge",
    "merit", "merry", "mesh", "metal", "metro", "mild", "mile", "milk",
    "mill", "mind", "mine", "mingle", "mini", "mink", "mint", "mirth",
    "miso", "miss", "mist", "mixer", "moat", "model", "modem", "moist",
    "mole", "mom", "money", "monk", "month", "moon", "moor", "moose", "morn",
    "moss", "motif", "motor", "mound", "mount", "mouse", "mouth", "move",
    "mug", "mule", "mural", "muse", "mushy", "music", "must", "myth",
    "nail", "name", "nap", "napkin", "narrow", "navel", "navy", "near",
    "neat", "neck", "needle", "neon", "nerve", "nest", "net", "news", "next",
    "nibble", "nice", "night", "ninja", "noble", "nomad", "noon", "norm",
    "north", "nose", "notch", "note", "novel", "nude", "nut", "oak", "oasis",
    "oat", "ocean", "octave", "octopus", "offer", "office", "olive", "omega",
    "onion", "open", "opera", "orbit", "orca", "order", "organ", "other",
    "otter", "ounce", "oval", "oven", "owl", "owner", "ox", "oxygen",
    "oyster", "ozone", "pace", "pack", "pact", "pad", "paddle", "page",
    "pail", "pain", "paint", "pair", "palm", "panda", "panel", "panic",
    "pansy", "pant", "paper", "park", "parrot", "parse", "party", "pass",
    "past", "pasta", "patch", "path", "patron", "pause", "paw", "pawn", "pay",
    "peace", "peach", "peak", "pear", "pearl", "peat", "peck", "pedal",
    "peek", "peel", "pelt", "pen", "penny", "peony", "people", "pep",
    "pepper", "perch", "perk", "perm", "pest", "petal", "pew", "phase",
    "phone", "photo", "pier", "pig", "pike", "pile", "pill", "pilot", "pin",
    "pinch", "pine", "ping", "pint", "pipe", "pirate", "pit", "pitch", "pity",
    "pivot", "pixel", "pizza", "place", "plain", "plan", "plank", "plant",
    "plate", "play", "plaza", "plea", "please", "pluck", "plum", "plume",
    "plus", "poach", "pocket", "pod", "poem", "point", "pole", "polka",
    "pond", "pony", "pool", "poppy", "porch", "pork", "port", "post",
    "pouch", "pound", "pour", "power", "prank", "pray", "press", "price",
    "pride", "prime", "print", "prior", "prism", "prize", "probe", "prom",
    "proof", "prop", "prose", "proud", "prove", "prowl", "proxy", "prune",
    "public", "puck", "puff", "puma", "pump", "punch", "pupil", "puppy",
    "pure", "purse", "push", "put", "putty", "quack", "quail", "quake",
    "quartz", "queen", "query", "quest", "queue", "quick", "quiet", "quill",
    "quilt", "quiz", "quota", "quote", "rabbit", "race", "rack", "radar",
    "radio", "raft", "rag", "rail", "rain", "raise", "rake", "rally", "ramp",
    "ranch", "range", "rapid", "rare", "rash", "rat", "rate", "raven", "raw",
    "ray", "razor", "read", "real", "reap", "rebel", "reed", "reef", "reel",
    "relay", "relic", "relish", "renew", "rent", "reply", "rerun", "rest",
    "retro", "rhino", "rhyme", "rib", "rice", "rich", "ride", "ridge",
    "rifle", "right", "rim", "ring", "rinse", "rip", "ripe", "rise", "risk",
    "rite", "ritz", "rival", "river", "road", "roam", "roar", "roast",
    "robot", "rock", "rodeo", "role", "roll", "roof", "rook", "room", "root",
    "rope", "rose", "rosy", "rotor", "rough", "round", "route", "rover",
    "row", "royal", "rude", "rug", "rugby", "rule", "rum", "rumor", "run",
    "rune", "runt", "rural", "rush", "rust", "sable", "sad", "safe",
    "sage", "sail", "saint", "salad", "salmon", "salt", "same", "sample",
    "sand", "satin", "sauce", "save", "scale", "scan", "scarf", "scene",
    "scent", "scold", "scoop", "scope", "score", "scout", "scrap", "scrub",
    "sea", "seal", "seam", "seat", "seed", "seek", "self", "sell", "send",
    "sense", "sepal", "seven", "sew", "shack", "shade", "shaft", "shake",
    "shallow", "shame", "shape", "shard", "share", "shark", "sharp", "shawl",
    "sheep", "sheet", "shelf", "shell", "shield", "shine", "ship", "shirt",
    "shoal", "shock", "shoe", "shoot", "shop", "shore", "short", "shout",
    "show", "shrew", "shrub", "shrug", "shuffle", "sick", "side", "sieve",
    "sigh", "sight", "sign", "silk", "silly", "silo", "silt", "simple",
    "sing", "sink", "sir", "site", "six", "size", "skate", "ski", "skim",
    "skin", "skip", "skirt", "skull", "sky", "slack", "slap", "slash", "slate",
    "sleep", "sleet", "slice", "slide", "slim", "sling", "slip", "slope",
    "slow", "slug", "small", "smart", "smash", "smell", "smile", "smith",
    "smoke", "smoky", "smug", "snack", "snail", "snake", "snap", "snarl",
    "sneak", "sniff", "snore", "snow", "snug", "soap", "soar", "sob", "soccer",
    "sock", "soda", "sofa", "soft", "soil", "solar", "sole", "solid", "solo",
    "song", "soon", "soot", "sort", "soul", "sound", "soup", "sour", "south",
    "space", "spade", "span", "spare", "spark", "spawn", "speak", "spear",
    "speed", "spell", "spend", "spice", "spike", "spin", "spine", "spire",
    "splash", "split", "spoil", "spoke", "spoon", "sport", "spot", "spray",
    "spring", "sprout", "spy", "square", "squash", "squid", "stack", "stag",
    "stain", "stair", "stalk", "stamp", "stand", "star", "stare", "stash",
    "state", "stay", "steam", "steel", "steep", "step", "stick", "stiff",
    "still", "sting", "stir", "stitch", "stock", "stomp", "stone", "stool",
    "stop", "store", "storm", "story", "stove", "straw", "strip", "stud",
    "study", "stuff", "sturdy", "style", "sugar", "suit", "sum", "summit",
    "sun", "sunny", "super", "surf", "surge", "swag", "swamp", "swan", "swap",
    "swarm", "sway", "swear", "sweat", "sweep", "sweet", "swift", "swim",
    "swing", "swirl", "sword", "swore", "table", "tack", "tactic", "tag",
    "tail", "taint", "take", "tale", "talk", "tall", "tame", "tan", "tango",
    "tank", "tap", "tape", "target", "tarot", "tart", "task", "taste", "taut",
    "tax", "tea", "teach", "team", "tear", "tease", "teeth", "tempo", "tempt",
    "tenor", "tense", "tent", "term", "test", "text", "thank", "thaw", "them",
    "then", "there", "thick", "thief", "thigh", "thin", "thing", "think",
    "third", "thorn", "those", "three", "throne", "throw", "thumb", "thump",
    "tidy", "tie", "tiger", "tight", "tile", "till", "timer", "tin", "tiny",
    "tip", "tire", "title", "toad", "toast", "today", "toe", "tofu", "token",
    "told", "toll", "tomb", "ton", "tone", "tong", "tool", "tooth", "top",
    "topic", "torch", "torus", "toss", "total", "touch", "tough", "tour",
    "tow", "tower", "town", "toy", "trace", "track", "trade", "trail", "train",
    "trait", "trap", "trash", "tray", "treat", "tree", "trek", "trend", "trial",
    "tribe", "trick", "trim", "trip", "tripe", "trivia", "trout", "truck",
    "true", "trump", "trunk", "trust", "truth", "try", "tube", "tuck", "tulip",
    "tuna", "tune", "tunic", "turf", "turn", "tusk", "tutor", "tweed", "tweet",
    "twig", "twin", "twirl", "twist", "typo", "udon", "ultra", "umber", "uncle",
    "under", "unit", "unity", "upper", "urban", "usage", "use", "user", "usher",
    "utter", "vacant", "vague", "vain", "valid", "valor", "value", "van", "vane",
    "vapor", "vast", "vault", "veil", "vein", "velvet", "venom", "vent", "venue",
    "verb", "verge", "verse", "very", "vest", "vibe", "video", "view", "vigor",
    "villa", "vine", "vinyl", "viola", "virtue", "visa", "vise", "visit", "vital",
    "vivid", "vocal", "voice", "void", "vole", "volt", "vote", "vouch", "vowel",
    "voyage", "wade", "wafer", "wage", "wagon", "waist", "wait", "wake", "walk",
    "wall", "wallet", "walnut", "walrus", "wand", "want", "ward", "warm", "warn",
    "wart", "wash", "watch", "water", "wave", "wavy", "wax", "way", "weak",
    "wealth", "wear", "weasel", "weave", "web", "wedge", "weed", "week", "weigh",
    "weird", "well", "welsh", "west", "whale", "wharf", "wheat", "wheel", "when",
    "whim", "whip", "whirl", "whisk", "white", "whole", "why", "wick", "wide",
    "widow", "width", "wig", "wild", "will", "wilt", "wily", "wince", "wind",
    "wing", "wink", "winter", "wire", "wise", "wish", "wisp", "witch", "with",
    "wits", "wobble", "woke", "wolf", "woman", "wonder", "wood", "wool", "word",
    "work", "world", "worm", "worry", "worth", "wound", "wrap", "wrath", "wrench",
    "wrist", "write", "wrong", "xenon", "yacht", "yak", "yam", "yank", "yard",
    "yarn", "yawn", "year", "yeast", "yell", "yew", "yield", "yoga", "yogurt",
    "yolk", "young", "youth", "zebra", "zen", "zero", "zest", "zigzag", "zinc",
    "zip", "zombie", "zone", "zoom", "zucchini",
)
